// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bagus-aulia/inventhier/internal/core/dto/product"
	mock "github.com/stretchr/testify/mock"
)

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

type ProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductService) EXPECT() *ProductService_Expecter {
	return &ProductService_Expecter{mock: &_m.Mock}
}

// StockIn provides a mock function for the type ProductService
func (_mock *ProductService) StockIn(c context.Context, payload product.StockInPayload) error {
	ret := _mock.Called(c, payload)

	if len(ret) == 0 {
		panic("no return value specified for StockIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, product.StockInPayload) error); ok {
		r0 = returnFunc(c, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_StockIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StockIn'
type ProductService_StockIn_Call struct {
	*mock.Call
}

// StockIn is a helper method to define mock.On call
//   - c context.Context
//   - payload product.StockInPayload
func (_e *ProductService_Expecter) StockIn(c any, payload any) *ProductService_StockIn_Call {
	return &ProductService_StockIn_Call{Call: _e.mock.On("StockIn", c, payload)}
}

func (_c *ProductService_StockIn_Call) Run(run func(c context.Context, payload product.StockInPayload)) *ProductService_StockIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 product.StockInPayload
		if args[1] != nil {
			arg1 = args[1].(product.StockInPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_StockIn_Call) Return(err error) *ProductService_StockIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_StockIn_Call) RunAndReturn(run func(c context.Context, payload product.StockInPayload) error) *ProductService_StockIn_Call {
	_c.Call.Return(run)
	return _c
}
