// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bagus-aulia/inventhier/internal/core/dto/product"
	mock "github.com/stretchr/testify/mock"
)

// NewProductLogger creates a new instance of ProductLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductLogger {
	mock := &ProductLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductLogger is an autogenerated mock type for the ProductLogger type
type ProductLogger struct {
	mock.Mock
}

type ProductLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductLogger) EXPECT() *ProductLogger_Expecter {
	return &ProductLogger_Expecter{mock: &_m.Mock}
}

// StoreProductLog provides a mock function for the type ProductLogger
func (_mock *ProductLogger) StoreProductLog(ctx context.Context, log product.ProductLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for StoreProductLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, product.ProductLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductLogger_StoreProductLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreProductLog'
type ProductLogger_StoreProductLog_Call struct {
	*mock.Call
}

// StoreProductLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log product.ProductLog
func (_e *ProductLogger_Expecter) StoreProductLog(ctx any, log any) *ProductLogger_StoreProductLog_Call {
	return &ProductLogger_StoreProductLog_Call{Call: _e.mock.On("StoreProductLog", ctx, log)}
}

func (_c *ProductLogger_StoreProductLog_Call) Run(run func(ctx context.Context, log product.ProductLog)) *ProductLogger_StoreProductLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 product.ProductLog
		if args[1] != nil {
			arg1 = args[1].(product.ProductLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductLogger_StoreProductLog_Call) Return(err error) *ProductLogger_StoreProductLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductLogger_StoreProductLog_Call) RunAndReturn(run func(ctx context.Context, log product.ProductLog) error) *ProductLogger_StoreProductLog_Call {
	_c.Call.Return(run)
	return _c
}
