// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bagus-aulia/inventhier/internal/core/dto/product"
	mock "github.com/stretchr/testify/mock"
)

// NewProductCache creates a new instance of ProductCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductCache {
	mock := &ProductCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductCache is an autogenerated mock type for the ProductCache type
type ProductCache struct {
	mock.Mock
}

type ProductCache_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductCache) EXPECT() *ProductCache_Expecter {
	return &ProductCache_Expecter{mock: &_m.Mock}
}

// DelProductCache provides a mock function for the type ProductCache
func (_mock *ProductCache) DelProductCache(ctx context.Context, sku string) error {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for DelProductCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductCache_DelProductCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelProductCache'
type ProductCache_DelProductCache_Call struct {
	*mock.Call
}

// DelProductCache is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
func (_e *ProductCache_Expecter) DelProductCache(ctx any, sku any) *ProductCache_DelProductCache_Call {
	return &ProductCache_DelProductCache_Call{Call: _e.mock.On("DelProductCache", ctx, sku)}
}

func (_c *ProductCache_DelProductCache_Call) Run(run func(ctx context.Context, sku string)) *ProductCache_DelProductCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductCache_DelProductCache_Call) Return(err error) *ProductCache_DelProductCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductCache_DelProductCache_Call) RunAndReturn(run func(ctx context.Context, sku string) error) *ProductCache_DelProductCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductBySKU provides a mock function for the type ProductCache
func (_mock *ProductCache) GetProductBySKU(ctx context.Context, sku string) (*product.Product, error) {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetProductBySKU")
	}

	var r0 *product.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*product.Product, error)); ok {
		return returnFunc(ctx, sku)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *product.Product); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductCache_GetProductBySKU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductBySKU'
type ProductCache_GetProductBySKU_Call struct {
	*mock.Call
}

// GetProductBySKU is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
func (_e *ProductCache_Expecter) GetProductBySKU(ctx any, sku any) *ProductCache_GetProductBySKU_Call {
	return &ProductCache_GetProductBySKU_Call{Call: _e.mock.On("GetProductBySKU", ctx, sku)}
}

func (_c *ProductCache_GetProductBySKU_Call) Run(run func(ctx context.Context, sku string)) *ProductCache_GetProductBySKU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductCache_GetProductBySKU_Call) Return(product1 *product.Product, err error) *ProductCache_GetProductBySKU_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *ProductCache_GetProductBySKU_Call) RunAndReturn(run func(ctx context.Context, sku string) (*product.Product, error)) *ProductCache_GetProductBySKU_Call {
	_c.Call.Return(run)
	return _c
}
