// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bagus-aulia/inventhier/internal/core/dto/product"
	mock "github.com/stretchr/testify/mock"
)

// NewProduct creates a new instance of Product. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *Product {
	mock := &Product{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Product is an autogenerated mock type for the Product type
type Product struct {
	mock.Mock
}

type Product_Expecter struct {
	mock *mock.Mock
}

func (_m *Product) EXPECT() *Product_Expecter {
	return &Product_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type Product
func (_mock *Product) CreateProduct(ctx context.Context, data product.Product) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, product.Product) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Product_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type Product_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - data product.Product
func (_e *Product_Expecter) CreateProduct(ctx any, data any) *Product_CreateProduct_Call {
	return &Product_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, data)}
}

func (_c *Product_CreateProduct_Call) Run(run func(ctx context.Context, data product.Product)) *Product_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 product.Product
		if args[1] != nil {
			arg1 = args[1].(product.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Product_CreateProduct_Call) Return(err error) *Product_CreateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Product_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, data product.Product) error) *Product_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductBySKU provides a mock function for the type Product
func (_mock *Product) GetProductBySKU(ctx context.Context, sku string) (*product.Product, error) {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetProductBySKU")
	}

	var r0 *product.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*product.Product, error)); ok {
		return returnFunc(ctx, sku)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *product.Product); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Product_GetProductBySKU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductBySKU'
type Product_GetProductBySKU_Call struct {
	*mock.Call
}

// GetProductBySKU is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
func (_e *Product_Expecter) GetProductBySKU(ctx any, sku any) *Product_GetProductBySKU_Call {
	return &Product_GetProductBySKU_Call{Call: _e.mock.On("GetProductBySKU", ctx, sku)}
}

func (_c *Product_GetProductBySKU_Call) Run(run func(ctx context.Context, sku string)) *Product_GetProductBySKU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Product_GetProductBySKU_Call) Return(product1 *product.Product, err error) *Product_GetProductBySKU_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *Product_GetProductBySKU_Call) RunAndReturn(run func(ctx context.Context, sku string) (*product.Product, error)) *Product_GetProductBySKU_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProductStock provides a mock function for the type Product
func (_mock *Product) UpdateProductStock(ctx context.Context, sku string, stockIn int, staffUUID string) error {
	ret := _mock.Called(ctx, sku, stockIn, staffUUID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProductStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) error); ok {
		r0 = returnFunc(ctx, sku, stockIn, staffUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Product_UpdateProductStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProductStock'
type Product_UpdateProductStock_Call struct {
	*mock.Call
}

// UpdateProductStock is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
//   - stockIn int
//   - staffUUID string
func (_e *Product_Expecter) UpdateProductStock(ctx any, sku any, stockIn any, staffUUID any) *Product_UpdateProductStock_Call {
	return &Product_UpdateProductStock_Call{Call: _e.mock.On("UpdateProductStock", ctx, sku, stockIn, staffUUID)}
}

func (_c *Product_UpdateProductStock_Call) Run(run func(ctx context.Context, sku string, stockIn int, staffUUID string)) *Product_UpdateProductStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Product_UpdateProductStock_Call) Return(err error) *Product_UpdateProductStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Product_UpdateProductStock_Call) RunAndReturn(run func(ctx context.Context, sku string, stockIn int, staffUUID string) error) *Product_UpdateProductStock_Call {
	_c.Call.Return(run)
	return _c
}
