// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserV1Handler_GetUser_FullMethodName = "/user_v1_grpc.UserV1Handler/GetUser"
)

// UserV1HandlerClient is the client API for UserV1Handler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserV1HandlerClient interface {
	GetUser(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Data, error)
}

type userV1HandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserV1HandlerClient(cc grpc.ClientConnInterface) UserV1HandlerClient {
	return &userV1HandlerClient{cc}
}

func (c *userV1HandlerClient) GetUser(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, UserV1Handler_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserV1HandlerServer is the server API for UserV1Handler service.
// All implementations must embed UnimplementedUserV1HandlerServer
// for forward compatibility
type UserV1HandlerServer interface {
	GetUser(context.Context, *Params) (*Data, error)
	mustEmbedUnimplementedUserV1HandlerServer()
}

// UnimplementedUserV1HandlerServer must be embedded to have forward compatible implementations.
type UnimplementedUserV1HandlerServer struct {
}

func (UnimplementedUserV1HandlerServer) GetUser(context.Context, *Params) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserV1HandlerServer) mustEmbedUnimplementedUserV1HandlerServer() {}

// UnsafeUserV1HandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserV1HandlerServer will
// result in compilation errors.
type UnsafeUserV1HandlerServer interface {
	mustEmbedUnimplementedUserV1HandlerServer()
}

func RegisterUserV1HandlerServer(s grpc.ServiceRegistrar, srv UserV1HandlerServer) {
	s.RegisterService(&UserV1Handler_ServiceDesc, srv)
}

func _UserV1Handler_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1HandlerServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserV1Handler_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1HandlerServer).GetUser(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

// UserV1Handler_ServiceDesc is the grpc.ServiceDesc for UserV1Handler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserV1Handler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_v1_grpc.UserV1Handler",
	HandlerType: (*UserV1HandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserV1Handler_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
