// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bagus-aulia/go-tools/tools/handler/response"
	"github.com/bagus-aulia/inventhier/internal/core/dto/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// Checkout provides a mock function for the type PaymentClient
func (_mock *PaymentClient) Checkout(ctx context.Context, payload payment.CheckoutPayload) (response.Response[*payment.CheckoutResp], error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 response.Response[*payment.CheckoutResp]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.CheckoutPayload) (response.Response[*payment.CheckoutResp], error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.CheckoutPayload) response.Response[*payment.CheckoutResp]); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(response.Response[*payment.CheckoutResp])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.CheckoutPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentClient_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type PaymentClient_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - payload payment.CheckoutPayload
func (_e *PaymentClient_Expecter) Checkout(ctx any, payload any) *PaymentClient_Checkout_Call {
	return &PaymentClient_Checkout_Call{Call: _e.mock.On("Checkout", ctx, payload)}
}

func (_c *PaymentClient_Checkout_Call) Run(run func(ctx context.Context, payload payment.CheckoutPayload)) *PaymentClient_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.CheckoutPayload
		if args[1] != nil {
			arg1 = args[1].(payment.CheckoutPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentClient_Checkout_Call) Return(response1 response.Response[*payment.CheckoutResp], err error) *PaymentClient_Checkout_Call {
	_c.Call.Return(response1, err)
	return _c
}

func (_c *PaymentClient_Checkout_Call) RunAndReturn(run func(ctx context.Context, payload payment.CheckoutPayload) (response.Response[*payment.CheckoutResp], error)) *PaymentClient_Checkout_Call {
	_c.Call.Return(run)
	return _c
}
