// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewRedisInterface creates a new instance of RedisInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisInterface {
	mock := &RedisInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedisInterface is an autogenerated mock type for the RedisInterface type
type RedisInterface struct {
	mock.Mock
}

type RedisInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisInterface) EXPECT() *RedisInterface_Expecter {
	return &RedisInterface_Expecter{mock: &_m.Mock}
}

// DelRedisData provides a mock function for the type RedisInterface
func (_mock *RedisInterface) DelRedisData(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DelRedisData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisInterface_DelRedisData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelRedisData'
type RedisInterface_DelRedisData_Call struct {
	*mock.Call
}

// DelRedisData is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *RedisInterface_Expecter) DelRedisData(ctx any, key any) *RedisInterface_DelRedisData_Call {
	return &RedisInterface_DelRedisData_Call{Call: _e.mock.On("DelRedisData", ctx, key)}
}

func (_c *RedisInterface_DelRedisData_Call) Run(run func(ctx context.Context, key string)) *RedisInterface_DelRedisData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RedisInterface_DelRedisData_Call) Return(err error) *RedisInterface_DelRedisData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisInterface_DelRedisData_Call) RunAndReturn(run func(ctx context.Context, key string) error) *RedisInterface_DelRedisData_Call {
	_c.Call.Return(run)
	return _c
}

// GetRedisData provides a mock function for the type RedisInterface
func (_mock *RedisInterface) GetRedisData(ctx context.Context, key string, destination interface{}) error {
	ret := _mock.Called(ctx, key, destination)

	if len(ret) == 0 {
		panic("no return value specified for GetRedisData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = returnFunc(ctx, key, destination)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisInterface_GetRedisData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRedisData'
type RedisInterface_GetRedisData_Call struct {
	*mock.Call
}

// GetRedisData is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - destination interface{}
func (_e *RedisInterface_Expecter) GetRedisData(ctx any, key any, destination any) *RedisInterface_GetRedisData_Call {
	return &RedisInterface_GetRedisData_Call{Call: _e.mock.On("GetRedisData", ctx, key, destination)}
}

func (_c *RedisInterface_GetRedisData_Call) Run(run func(ctx context.Context, key string, destination interface{})) *RedisInterface_GetRedisData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RedisInterface_GetRedisData_Call) Return(err error) *RedisInterface_GetRedisData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisInterface_GetRedisData_Call) RunAndReturn(run func(ctx context.Context, key string, destination interface{}) error) *RedisInterface_GetRedisData_Call {
	_c.Call.Return(run)
	return _c
}

// SetRedisData provides a mock function for the type RedisInterface
func (_mock *RedisInterface) SetRedisData(ctx context.Context, key string, data string, timeout time.Duration) error {
	ret := _mock.Called(ctx, key, data, timeout)

	if len(ret) == 0 {
		panic("no return value specified for SetRedisData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, data, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisInterface_SetRedisData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRedisData'
type RedisInterface_SetRedisData_Call struct {
	*mock.Call
}

// SetRedisData is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data string
//   - timeout time.Duration
func (_e *RedisInterface_Expecter) SetRedisData(ctx any, key any, data any, timeout any) *RedisInterface_SetRedisData_Call {
	return &RedisInterface_SetRedisData_Call{Call: _e.mock.On("SetRedisData", ctx, key, data, timeout)}
}

func (_c *RedisInterface_SetRedisData_Call) Run(run func(ctx context.Context, key string, data string, timeout time.Duration)) *RedisInterface_SetRedisData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RedisInterface_SetRedisData_Call) Return(err error) *RedisInterface_SetRedisData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisInterface_SetRedisData_Call) RunAndReturn(run func(ctx context.Context, key string, data string, timeout time.Duration) error) *RedisInterface_SetRedisData_Call {
	_c.Call.Return(run)
	return _c
}
